parameters:
#    kd1_task.example.class: kd1\TaskBundle\Example

services:
#    kd1_task.example:
#        class: %kd1_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
